esphome:
  name: puertagaraje
  friendly_name: Puerta Garaje

esp32:
  board: esp32dev
  framework:
    type: esp-idf 
  
#wifi: 
#  ssid:  DOMOTICACASA
#  password: "33333333"
#  reboot_timeout: 0s

logger:
  level: INFO

#Enable Home Assistant API
#api:
#  reboot_timeout: 0s
#  encryption:
#    key: "Jokv+sef/jexoCyDaNj/b4RDGbAIysZv/o4IboDkzi4="
    
#ota:
#  - platform: esphome
#    password: "5523434a"
    
#web_server:
#  port: 80

# Globals to store learned signals
globals:
  - id: learned_code
    type: std::vector<int32_t>
    restore_value: false
    initial_value: "{2638, -392, 2616, -369, 2643, -378, 2601, -374, 2644, -382, 2622, -359, 2644, -380, 370, -2624, 2628, -380, 369, -2642, 2605, -382, 369, -2642, 2606, -383, 370, -2642, 377, -2598, 374, -2642, 2609, -384, 371}"
  - id: learning_mode
    type: bool
    initial_value: 'false'
  - id: signal_learned
    type: bool
    initial_value: 'false'
  - id: repeat_counter
    type: int
    restore_value: no
    initial_value: '60'

interval:
  - interval: 3s
    then:
      - if:
          condition:
            lambda: 'return id(repeat_counter) >= 0;'
          then:
            - lambda: |-
                ESP_LOGI("replay", "Pending executions #%d", id(repeat_counter));
                id(repeat_counter)--;
            - lambda: |-
                if (id(learned_code).empty()) {
                  ESP_LOGW("replay", "No signal learned yet!");
                  return;
                }
                
                std::string preview = "";
                int count1 = 0;
                for (int32_t val : id(learned_code)) {
                  if (count1 > 0) preview += ", ";
                  preview += std::to_string(val);
                  count1++;
                  if (count1 >= 50) {
                    preview += "... (" + std::to_string(id(learned_code).size()) + " total)";
                    break;
                  }
                }
                ESP_LOGI("replay","Sending signal :  Size: %d. Signal: [%s]", id(learned_code).size(), preview.c_str());
                
            - remote_transmitter.transmit_raw:
                carrier_frequency: 0Hz
                code: !lambda 'return id(learned_code);'
  - interval: 15s
    then:
      - lambda: |-
          id(repeat_counter_read)->set_value({
            (uint8_t)(id(repeat_counter)),
            (uint8_t)(id(repeat_counter) >> 8),
            (uint8_t)(id(repeat_counter) >> 16),
            (uint8_t)(id(repeat_counter) >> 24)
          });

          id(repeat_counter_read)->notify();
    

esp32_ble:
  io_capability: none
  enable_on_boot: true
  
esp32_ble_server:
  id: puertagaraje
  manufacturer: "ESP32"
  model: "ESP32"
  firmware_version: "1.0.0"
  max_clients: 3 
  on_connect:
    - lambda: |-
        ESP_LOGI("BLE", "Connection started!");
  on_disconnect:
    - lambda: |-
        ESP_LOGI("BLE", "Connection finished!");
  services:
    - uuid: "180F"
      advertise: true
      characteristics:
        - uuid: "1801"
          id: open_the_door
          description: "Button pressed"
          write: true
          notify: true
          on_write:
            then:
                - lambda: |-
                    id(repeat_counter) = 60;
                    ESP_LOGI("BLE", "Repeat_counter set to %d", id(repeat_counter));
        - uuid: "1802"
          id: repeat_counter_read
          description: "Seconds since last PING"
          read: true
          notify: true
          value: !lambda |-
                    uint32_t val = id(repeat_counter);
                    ESP_LOGI("BLE", "Repeat_counter value: %d", id(repeat_counter));
                    return {(uint8_t)(val), (uint8_t)(val >> 8), (uint8_t)(val >> 16), (uint8_t)(val >> 24)};
                    
        - uuid: "1803"
          id: learn_code_start
          description: "Learn code start"
          write: true
          notify: true
          on_write:
            then:
                - lambda: |-
                    id(learning_mode) = true;
                    ESP_LOGI("BLE", "Learning mode ON - press your remote");
        - uuid: "1804"
          id: learn_code_end
          description: "Learn code end"
          write: true
          notify: true
          on_write:
            then:
                - lambda: |-
                    id(learning_mode) = false;
                    ESP_LOGI("BLE", "Learning mode OFF");
        - uuid: "1805"
          id: return_learn_code
          description: "Return learnt code"
          read: true
          notify: true
          value: !lambda |-
          
                std::string preview = "";
                int count1 = 0;
                for (int32_t val : id(learned_code)) {
                  if (count1 > 0) preview += ", ";
                  preview += std::to_string(val);
                  count1++;
                  if (count1 >= 50) {
                    preview += "... (" + std::to_string(id(learned_code).size()) + " total)";
                    break;
                  }
                }
                ESP_LOGI("raw_code","Current signal:  Size: %d. Signal: [%s]", id(learned_code).size(), preview.c_str());
            
                std::vector<uint8_t> out;
                int count2 = 0;
                for (int32_t val : id(learned_code)) {
                  out.push_back((val >> 24) & 0xFF);
                  out.push_back((val >> 16) & 0xFF);
                  out.push_back((val >> 8) & 0xFF);
                  out.push_back(val & 0xFF);
                  if (++count2 >= 3) break;
                }
                return out;
                    
# SPI Bus
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# CC1101 - Dual Pin Mode
cc1101:
  id: cc1101_module
  cs_pin: GPIO5
  frequency: 433.92MHz
  output_power: 11
  modulation_type: ASK/OOK
  symbol_rate: 5000
  filter_bandwidth: 200kHz

# Remote Receiver - connected to GDO2
remote_receiver:
  id: rf_receiver
  pin: GPIO2
  tolerance: 50%
  filter: 200us
  dump:
    - raw
  idle: 10ms
  on_raw:
    then:
      - lambda: |-
          // Log as single copyable line for YAML
          std::string code_str = "";
          for (int i = 0; i < x.size(); i++) {
            if (i > 0) code_str += ", ";
            code_str += std::to_string(x[i]);
          }
          //ESP_LOGI("raw_code", "Pulses: %d", x.size());
          //ESP_LOGI("raw_code", "Copy this line:");
          //ESP_LOGI("raw_code", "[%s]", code_str.c_str());
          
          // Learning mode logic
          if (id(learning_mode)) {
          
            if (x.size() < 10) {
                ESP_LOGI("raw_code", "Signal too short (%d elements), ignoring.", x.size());
                return;
            }
  
            id(learned_code).clear();
            for (int32_t val : x) {
              id(learned_code).push_back(val);
            }
            id(signal_learned) = true;
            id(learning_mode) = false;
           
           
            std::string preview = "";
            int count = 0;
            for (int32_t val : id(learned_code)) {
              if (count > 0) preview += ", ";
              preview += std::to_string(val);
              count++;
              if (count >= 20) {
                preview += "... (" + std::to_string(id(learned_code).size()) + " total)";
                break;
              }
            }
            
            ESP_LOGI("raw_code","Signal learned! Size: %d. Signal: [%s]", id(learned_code).size(), preview.c_str());
            
          }
          
# Remote Transmitter - connected to GDO0
remote_transmitter:
  id: rf_transmitter
  pin: GPIO4
  carrier_duty_percent: 100%
  on_transmit:
    then:
      - cc1101.begin_tx: cc1101_module
  on_complete:
    then:
      - cc1101.begin_rx: cc1101_module


switch:
  - platform: template
    name: "Learning Mode"
    id: learning_mode_switch
    icon: "mdi:school"
    lambda: 'return id(learning_mode);'
    turn_on_action:
      - lambda: |-
          id(learning_mode) = true;
      - logger.log: "Learning mode ON - press your remote"
    turn_off_action:
      - lambda: |-
          id(learning_mode) = false;
      - logger.log: "Learning mode OFF"
      
button:
  - platform: restart
    name: "Restart"


  - platform: template
    name: "Send Signal"
    icon: "mdi:replay"
    on_press:
      - lambda: |-
          id(repeat_counter)=60;
          ESP_LOGI("BLE", "repeat_counter reset to %d", id(repeat_counter));


 
sensor:
  - platform: template
    name: "Signal length"
    id: signal_length
    icon: "mdi:counter"
    unit_of_measurement: "pulses"
    lambda: 'return id(learned_code).size();'
    update_interval: 5s
    
